# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$time\
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$kubernetes\
$aws\
$gcloud\
$openstack\
$azure\
$direnv\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$status\
$os\
$container\
$shell\
$character"""

[username]
disabled = true

[hostname]
disabled = true

[kubernetes]
disabled = false
format = '[$symbol$context( \($namespace\))]($style) '
symbol = '󱃾 '
style = 'green'

[gcloud]
symbol = '󱇶 '
style = 'blue'

[terraform]
symbol = ' '

[time]
disabled = false
format = '[$time]($style) '
time_format = "%R"
style = 'yellow'

[character]
format = "$symbol "
success_symbol = "[◉](bold green)"
error_symbol = "[⊘](bold red)"

[cmd_duration]
format = "[$duration](dimmed white)"
